### ISSUE TITLE
Insert licence into source code

### ISSUE THREAD

**Issue by omron93** [snowballstem/snowball#10]
Could you please inset licence into distributed source code?

Because BSD licence requires including its text with all derivative works. So without including a proper full license text it is making difficult or impossible for anyone to comply with desired license terms.

There was discussion on old mailing list - http://thread.gmane.org/gmane.comp.search.snowball/1463

Thanks,
Marek

**Comment by omron93** [comment]
Is this acceptable?

**Comment by ojwb** [comment]
Unfortunately it's more complex than that.  It's something I'd like to resolve, but I've been very busy since taking over snowball maintenance and have not had time to work on it yet.

http://snowball.tartarus.org/license.php says:

```
 All the software given out on this Snowball site is covered by the BSD License (see http://www.opensource.org/licenses/bsd-license.html ), with Copyright (c) 2001, Dr Martin Porter, and (for the Java developments) Copyright (c) 2002, Richard Boulton.
```

There are actually more copyright holders than that (for example, my contributions are substantial enough to be subject to copyright), but people who contributed code to be made available from the Snowball site can probably be assumed to be happy with it being made available under this advertised licence (I am intending to check this assumption is legally valid).

Unfortunately, there's also code contributed to the repos on github directly (for example, the cmake build system PR) which has never been made available from the Snowball website.  Since there's currently no licence specified in the github repo, so we don't even have the implied licence we do for contributions made to the version on the Snowball site.

So we need to check for such contributions, and ask for an explicit license, or else remove them if we can't contact the author, or if they aren't willing or able to grant such a license.

We should also make sure to explicitly ask for a licence grant for new contributions before merging any more non-trivial PRs.

If you want to help move this forwards, checking the PR list and commit log for such contributions and contacting the contributors would be very useful.

**Comment by omron93** [comment]
And what should this "licence grant" consist of? Is there any document contributors should fill,...? (I don't understand similar licensing process much)

**Comment by stefanor** [comment]
As a stopgap, you could maybe say "Copyright Dr Martin Porter, Richard Boulton and contributors"? That's what many projects do, to avoid listing every contributor.

Of course, it'd still be ideal to list every contributor (probably in a separate file, to avoid unnecessary duplication)

**Comment by ojwb** [comment]
The main issue isn't with exhaustively listing contributors or not, but that it isn't clear that all the contributors have actually licensed their contributions under the appropriate licence.

It's a rather annoying situation in which we can't put a license on the project until we confirm that the contributions are licensed as that, but until we do we'll need to get an explicit licence stated for contributions we merge (or else make the situation worse).

@omron93 I'm not a copyright lawyer, but I'd think an email, or a comment on the PR in which the code was submitted, from them stating that they hold the copyright on their contribution and that they agree to license it under the 2-clause version of the BSD licence as described at: http://www.opensource.org/licenses/bsd-license.html

If anyone isn't the copyright holder (for example, if it's owned by their employer) they'll need to get agreement of the copyright holder.

If anyone doesn't agree, I think we probably have to just drop their contribution.  There haven't been a huge number since moving to github, and for those I've merged I think I've asked about licensing in the PR before merging.

Thanks for looking into this.

**Comment by stefanor** [comment]
Oh, sorry, I missed that your concern was recent contributions via GitHub, not historic contributions. Yes, that's an issue.

There is the option of just adding a BSD license, and contacting all the recent contributors to say that this has happened. If they object, you can back out their contributions. This is pretty much what you have to do, if you contact them before adding the license file, too...

**Comment by ojwb** [comment]
> There is the option of just adding a BSD license, and contacting all the recent contributors to say that this has happened. If they object, you can back out their contributions. This is pretty much what you have to do, if you contact them before adding the license file, too...

That would be misleading downloaders as to the licensing situation though, so I don't want to do that.

We need to contact them (or remove their contributions) either way, but the right order to do it in is to ask them first.

I've just become aware of an extra little complication - the link on the snowball site to the licence text currently points to BSD 2 clause, but that URL used to give the BSD 3 clause license (which is pretty unhelpful of OSI).  But people contributing code before the URL changed will have implicitly contributed it as BSD 3 clause, so that is the licence we actually have overall.  I'll try to get this situation resolved on the "frozen" snowball site too.

These are the commits made since the move to github which we don't have a licence for:

```
a5c68f31  Jake Waksbaum user env perl instead of /usr/bin/perl
4bc9f365  Vsevolod Stakhov Make snowball library self-contained.
558c3691  Vsevolod Stakhov Use current directories in cmake.
d178f201  Vsevolod Stakhov Rework modules generation.
8f53cf66  Vsevolod Stakhov Fix cmake build.
ffc12ead  Vsevolod Stakhov Add initial cmake script.
fd50dcc2  Oerd Cukalla Add Travis-CI support
```

The top commit is a trivial and mechanical change, so there's only actually 2 people we really need to ask.  I assume nobody's contacted any of them already?  If not, I'll contact them this week.
