### ISSUE TITLE
python AttributeError snowballstemmer.algorithms()

### ISSUE THREAD

**Issue by kkaiser** [snowballstem/snowball#132]
Hello,

I installed the library from [PyPI](https://pypi.org/project/snowballstemmer/)
```
pip install snowballstemmer
```

There is a bug in https://github.com/snowballstem/snowball/blob/master/python/create_init.py#L42

```
----> 1 snowballstemmer.algorithms()

     67         return Stemmer.language()
     68     else:
---> 69         return list(_languages.key())
     70
     71 def stemmer(lang):

AttributeError: 'dict' object has no attribute 'key'
```

It should be `_languages.keys()`

**Comment by TTRh** [comment]
would it be possible to have a new python release including this fix ?

**Comment by mitya57** [comment]
@ojwb I can do a new Python release if needed. But I don’t want Python releases to diverge much from snowball releases. Because, for example, in Debian we are now building the Python package from main snowball source. So if some Python projects start to depend on, say, `snowball >= 2.0.1`, we will not be able to satisfy that requirement.

So my question is: are you planning to create a new release/tag? If no, do you think I should still do a Python release? And what version I should use: 2.0.1 or 2.0.0.1? The latter will make sense if there will be a 2.0.1 snowball release at some point.

**Comment by ojwb** [comment]
I'm hoping to make a new release soon (over a year is too long between releases), but currently it's waiting for some issues with the new Yiddish stemmer to be resolved, which is waiting for the author of that stemmer (#140).

I don't want to release with a new stemmer with unresolved issues.  I guess I could back out or disable that, but I'm really short of spare time currently so hesitant to create more work for myself.  I'll ping about the Yiddish stemmer and see if that's likely to get resolved soon.

**Comment by ojwb** [comment]
An update:

The Yiddish stemmer issues have now been addressed, and I've also merged a pending branch to make `hop` work as documented and the new Ada backend, which were both waiting on the Yiddish changes.

I'm going to try to also merge in the Armenian stemmer which I noticed was only on the website and not in the distribution as that shouldn't take long, so I should have a release out in the next day or two unless a show stopper crops up.  We've been including this in Xapian since 2011.

BTW, I'm planning to number it 2.1.0 since there's a minor upwardly compatible extension to the language - you can now use `sizeof` and `lenof` on string literals (which previously wasn't supported and gave an error).

@mitya57 If you need to create a python-specific version number in future, I'd suggest going for a 4 component one if pypi, etc support that.

**Comment by ojwb** [comment]
@mitya57 I've updated ready for 2.1.0 and pushed to git master on the snowball repo.

Assuming CI passes, this is likely to be what's released as 2.1.0.  If you have a chance please take and look and let me know if you see any problems with Python.

I've reinstated the list of natural languages PyPI doesn't know about since that appears to include Armenian and Yiddish, which are two of the three new algorithms.

**Comment by mitya57** [comment]
I see you already released 2.1.0, thanks! I will look at Python stuff and upload to PyPI a bit later today.

**Comment by mitya57** [comment]
Done now: https://pypi.org/project/snowballstemmer/2.1.0/. This is just `make dist_libstemmer_python` against the v2.1.0 tag, no changes were required.

**Comment by ojwb** [comment]
Great, thanks.
