### ISSUE TITLE
problems with Turkish stemmer 

### ISSUE THREAD

**Issue by tilneyyang** [snowballstem/snowball#18]
After trying the Turkish stemmer, I found there might be some inconsistencies with the original paper 'An Affix Stripping Morphological Analyzer for Turkish'. 
Here a some error examples:

<pre><code>
Yazacağım->Yazacak // should stem to Yaz, acak is a tense suffix
Yazıyorsunuz-> Yaziyor// should stem to Yazi, yor is a tense suffix 
</code></pre>

Both examples above derive from Yazi(write).

Above all, thanks a lot for the hard word to help people  analyse languages they don't even know much.

**Comment by ojwb** [comment]
The comment at the top of the stemmer's snowball source says it "based on" that paper.  If you read the paper describing the snowball implementation (see the "Accompanying description" link at https://snowballstem.org/algorithms/turkish/stemmer.html) this explains that:

> There are over thirty different suffixes classified in these two general groups of suffixes. The stemming algorithm covers only these suffixes that are appended to noun stems, since finding noun stems is essential for our information retrieval purposes.
[...]
> As mentioned before, Turkish stemmer described in this study stems only noun and nominal verb suffixes. The stemmer can be enhanced to stem all kinds of verb suffixes. In Turkish, there are over fifty suffixes that can be affixed to verbs [2]. The morphological structure of verb suffixes is more complicated than noun suffixes. Despite this, one can use the methodology presented in this paper to enhance the stemmer to find stems of all kinds of Turkish words. As mentioned earlier, finding stems of nouns and nominal verbs is sufficient for our purposes.

(The [2] above is a reference to the original paper you mention).

So these omissions seem to be a deliberate choice in the implementation rather than a bug.

It would be interesting to have a full implementation of the algorithm in the original paper if you were interested in contributing one, though it would probably be somewhat slower due to having to check a lot more suffixes.

**Comment by ojwb** [comment]
I've improved the page on the website describing this stemmer to make it clearer that it's not a full implementation of the Eryigit and Adali paper:

https://snowballstem.org/algorithms/turkish/stemmer.html

As I said above a full implementation would be interesting if you (or anyone else) are interested in contributing one, but I think the reported issue has now been addressed so closing.
