### ISSUE TITLE
Invalid generated Java

### ISSUE THREAD

**Issue by dscorbett** [snowballstem/snowball#30]
The Java file generated from this source:

``` snowball
externals (null)
define null as ()
```

contains this invalid method definition:

``` java
    public boolean null() {
        // (, line 2
        return true;
    }
```

**Comment by ojwb** [comment]
Did you actually hit this issue in real use?

While Snowball can be thought of as a general purpose string manipulation language, I'm not aware of any uses that aren't the stemmers, where the only external is always called `stem` anyway.  You can call a routine `null` as routines all get an `r_` prefix (which we can easily do for routines as they're only internally visible, so we also generate all the references to them).

The sanest "fix" I can currently see is just document this as a potential issue when choosing `external` names if you're using Snowball outside of the stemmers.

**Comment by dscorbett** [comment]
No, I only noticed it while reviewing the Java generator. It would indeed be easy to work around. This issue exists in the C generator as well, but it is not a problem there because of `-eprefix`.

**Comment by ojwb** [comment]
For C, `-eprefix` works around the flat namespace - otherwise all the stemmers would export a `stem` symbol and those would collide.  For languages with classes, having an object for each Snowball program and the externals as methods of that object addresses that particular problem (and specifying the classname to use is necessary instead).

I guess `-eprefix` could be hooked up for all the languages though.

I'd like to get a post-fork release out, so short term I think a note in the `snowman` document will do.

**Comment by erny1790** [comment]
Sorry I cannot find in the repository the "ext" folder for "englishStemmer.java", where I can get it?

**Comment by ojwb** [comment]
I've now documented this issue in the manual, and update the website with the latest manual.

At least currently Snowball's domain is stemmers, and there the established pattern is a single external called `stem` which isn't a reserved word in any language I'm aware of.  So this problem seems essentially theoretical and supporting `-eprefix` beyond the C backend isn't worth the effort.  It's better to chose the external names with a little care than have to prefix them.
