### ISSUE TITLE
Stemmer for Occitan language in Java for SolR, code generated doesn't compile

### ISSUE THREAD

**Issue by Domenge** [snowballstem/snowball#67]
I am trying to write a Stemmer for the Occitan language very close the Catalan language but I can't.
There is a difference in the Among signature between the java code generated and what is used in the SolR buid chain. 
Where can I get the accurate version of the compiler in order to generate the good one ?
For example
/* CatalanStemmer  from SolR code */
@SuppressWarnings("unused") public class CatalanStemmer extends SnowballProgram {

private static final long serialVersionUID = 1L;

       /* patched */ private static final java.lang.invoke.MethodHandles.Lookup methodObject = java.lang.invoke.MethodHandles.lookup();  
                private final static Among a_0[] = {
                    new Among ( "", -1, 13, "", methodObject ),                                        
                    new Among ( "\u00B7", 0, 12, "", methodObject ),                                                              

/*OccitanStemmer generated by the compiler*/
public class OccitanStemmer extends org.tartarus.snowball.SnowballProgram {

    private static final long serialVersionUID = 1L;

    private final static Among a_0[] = {
        new Among("", -1, 13),

Again 
        among_var = find_among(a_0);
and 
        among_var = find_among_b(a_1);
are differents

**Comment by ojwb** [comment]
The first code looks like that generated by an older version of the compiler (before 0f9d3d64ab965447a7f638b8ededc924f3efca75), with a few extra changes (`@SuppressWarnings("unused")` and `/* patched */` aren't things we've ever generated).  I'd guess either solr uses a patched version of an old version of the snowball compiler (and they haven't contributed back those changes) or else they've manually modified the generated code from an old version of the compiler.

Either way, you'll need to talk to them about how to create code that works with their setup.  If you want to use the snowball compiler available here, we expect you to use the corresponding version on the runtime support files.  Essentially we regard the API of the runtime support as a private API.

> among_var = find_among(a_0);
> and
> among_var = find_among_b(a_1);

That difference is due to whether `among` is being used in forwards vs backwards mode.
