### ISSUE TITLE
Unreachable statement in generated Java code

### ISSUE THREAD

**Issue by dscorbett** [snowballstem/snowball#83]
The following Snowball code:
```snowball
externals (stem)
define stem as not true
```
produces invalid Java code:
```java
public boolean stem() {
    // not, line 2
    lab0: do {
        return false;
    } while (false);
    return true;
}
```
which does not compile:
```
org/tartarus/snowball/ext/testStemmer.java:23: error: unreachable statement
    return true;
    ^
```

**Comment by ojwb** [comment]
I'm thinking that rather than add more backend-specific code to handle this we'd do better to have a generic dead-code removal pass (which could also easily issue warnings when there's unreachable code, e.g. `'hello'` is unreachable in `define stem as not true 'hello'`), and explicitly represent the end of the function in the parse tree.

A basic building block for this is a way to determine if a given node always gives signal `f`, always gives signal `t`, or can give either signal.  This isn't too hard to code up (I had a quick go) and would always allow eliminating redundant `try` and the like (`try foo` where `foo` is a function which always returns signal `t` can be handled as if it were just `foo`; `do foo` -> `test foo`, which we can already handle as just `foo` if we can determine that `foo` always leaves the cursor unchanged).

Do you know of any non-artificial case we currently generate bad Java code for?  (Even if this only affects artificial cases it ought to be fixed - just wondering about how to prioritise this.)

**Comment by dscorbett** [comment]
While modifying the French stemmer, I wrote something of the form `try C1 or C2`, which was a bug but not an artificial one. I don’t think there’s any non-buggy case where Snowball currently generates bad Java.

**Comment by ojwb** [comment]
OK, so with my prototype

```
externals (stem)

define stem as (try 'un' or 're')
```

gives:

```
tests/dead-code-try.sbl:3: warning: OR always signals t here so following clauses are dead code
```

Which is good, though has usability issues as-is (adding column information to diagnostics would help a lot).

This example also supports my conclusion that trying to tweak the current per-backend reachability tracking isn't the way to go - I originally tried hooking up the existing `g->label_used` mechanism (which the C backend uses to avoid generate unused labels) for the Java backend, which addressed the `not true` case, but it felt brittle and indeed it doesn't solve this case.  And while it's easy to tweak it so it does handle this case, the whole approach relies on adding code to update the state correctly in too many places.

**Comment by ojwb** [comment]
I've checked and this is still an issue, though we now generate slightly different code for the example at the top:

```
public boolean stem() {
    lab0: {
        return false;
    }
    return true;
}
```

I'll try to get back to that branch...

**Comment by ojwb** [comment]
I've got my dead code removal to a state where it can be merged, and it addresses all the cases mentioned here as well as many others.  I suspect it's possible to create snowball programs which result in Java code that won't compile - if anyone finds example please report them (even if they're artificial).
