### ISSUE TITLE
Missing 'german2' stemming algorithm variant in the C version of the libstemmer library

### ISSUE THREAD

**Issue by jrabensc** [snowballstem/snowball#92]
Hi,

currently, the tarball of the C version of the libstemmer library is missing the 'german2' algorithm. Is there a particular reason for this?

Thanks!

**Comment by ojwb** [comment]
I'm not sure of the history of this, but `libstemmer/modules.txt` says:

```
# Some other stemmers in the snowball project are not included in the standard
# distribution. To compile a libstemmer with them in, add them to this list,
# and regenerate the distribution. (You will need a full source checkout for
# this.) They are included in the snowball website as curiosities, but are not
# intended for general use, and use of them is is not fully supported.  These
# algorithms are:
#
# german2          - This is a slight modification of the german stemmer.
#german2          UTF_8,ISO_8859_1        german2               german
```

(and then some others entries.)

And [the website](http://snowballstem.org/algorithms/german2/stemmer.html) says:

> In the sample German vocabulary of 35,000 words, the main stemmer and the
variant stemmer exhibit about 90 differences. Of these about half are in words
of foreign language origin (_raphael_, _poesie_ etc). Of the native German
words, about half seem to be improved by the variant stemming, and the other
half made worse. In any case the differences are little more than one word per
thousand among the native German words.

So I guess the reasoning was probably that it was an experiment which didn't seem to offer a clear improvement.

It would be easy to include if people actually want to use it though.

Or we could consider unifying the two algorithms in some way.

**Comment by jrabensc** [comment]
Thanks for your answer. I am using the R package SnowballC which uses those c libraries and therefore misses the german2 stemmer. I would really appreciate including the german2 stemmer.

**Comment by ojwb** [comment]
I did my own comparison of the output from german and german2 on `snowball-data/german/voc.txt` which has 35033 entries (so appears to be the same "sample German vocabulary of 35,000 words"; also the only change to this file since it was added to version control in 2005 has been to convert it to UTF-8).

Comparing the results from stemming this with german and german2, the first interesting thing is I get 77 different stems (rather than "about 90").  The algorithm has changed a little over time - there was an extra rule to handle "-nisse" in 2009 and a fix for a bug handing "qu" so that it matches the algorithm description.  I undid these two algorithm changes and got 76 different stems.  Maybe "90" was a typo for "80"?  I don't have a better theory.

I also noticed a significant proportion of foreign words, as well as some proper nouns. Some cases definitely seem improved, and quite a few are just different but effectively just change the stem for a word or group of words to a stem that isn't otherwise generated.  Contrary to that quote from the website however, I didn't spot any differences I would classify as clearly worse, though there are some changes that have good and bad aspects to them.

An example is that german2 changes "Bluet" (Allemanic German word for "blood") to stem to "blut" which is the same stem as "Blut" (German word for "blood"), so that seems beneficial.  The downside is that "Blüte" ("blossom") stems to "blut" with both the german and german2 algorithms, but this "Blut"/"Blüte" conflation is an already present minor problem so I think overall I'd view the change to "Bluet" as neutral at worst.

The replacing of umlauts with "e" suffixes is presumably much less common in newly created text than it once was as modern computer systems generally don't have the limitations which motivated this, but there will still be large amounts of legacy text so I think it makes sense to just replace german with german2.
