### ISSUE TITLE
Consider creating a change log

### ISSUE THREAD

**Issue by pbasista** [snowballstem/snowball#96]
Currently, there is no simple way to determine which changes have been made between the released versions. Consider creating a changelog which would contain this information.

**Comment by mitya57** [comment]
A problem is that there have been no officially released versions. Are you talking about snowball in general, or about the Python package on PyPI?

**Comment by pbasista** [comment]
Yes, I would be interested primarily in the Python package changelog, which has releases. But I can imagine that others may be interested in changes affecting other languages as well.

Therefore, I think that it may be reasonable to perhaps unify the versioning and releases across languages and provide a generic changelog containing all changes.

**Comment by mitya57** [comment]
The current release of Python package is the first release produced from this repository. The previous releases were produced from [this fork](https://github.com/shibukawa/snowball). That fork was based on a February 2013 state of snowball code, and there have been a lot of changes to the snowball code since then, so it would be difficult to enumerate them all in a changelog.

You can see the git log for changes to snowball code in general (such as addition of new natural languages), and history of [`generator_python.c`](https://github.com/snowballstem/snowball/commits/master/compiler/generator_python.c) and [`python` subdirectory](https://github.com/snowballstem/snowball/commits/master/python) for changes specific to the Python bindings. Also see the “Major Events” section on the homepage: https://snowballstem.org/.

For future Python releases, I will try to make a proper changelog if I will be making them separately from releases of snowball itself. But the long-term plan is to start making proper releases of snowball itself, as discussed in https://github.com/snowballstem/snowball/issues/93#issuecomment-504866298.
